server:
  port: 8003

spring:
  application:
    name: service-vod

  profiles:
    active: dev

  redis:
    host: ottofans.top
    port: 6379
    password: 'yl2vXBS%FjGoSfby'
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  cloud:
    nacos:
      discovery:
        server-addr: 47.104.235.180:8848