server:
  port: 8009

spring:
  application:
    name: service-statistic

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://natsuiroginga.work:3306/guli_edu?serverTimezone=Asia/Shanghai
    username: root
    password: yl2vXBS%FjGoSfby
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  redis:
    host: ottofans.top
    port: 6379
    password: 'yl2vXBS%FjGoSfby'

  jackson: # 时间: 东八区
    date-format: yyyy-MM-dd
    time-zone: GMT+8

  cloud:
    nacos:
      discovery:
        server-addr: 47.104.235.180:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
